#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {model_name}-deployment
spec:
  selector:
    matchLabels:
      app: {model_name}-server
  replicas: 3
  template:
    metadata:
      labels:
        app: {model_name}-server
    spec:
      containers:
      - name: {model_name}-container
        image: docker.io/{docker_user}/tensorflow-linear-model:{github.sha}
        ports:
        - containerPort: 8501
  
