name: Modelops deploy		
on:					
  push:		
    branches: [ main ]		
  pull_request:			
    branches: [ main ]	
#sadasdasdasd
jobs:
  build:
    runs-on: ubuntu-latest
    container: adsoft/aiops:latest
    steps:
      - uses: actions/checkout@v2
      
      - name: helloword 
        run: echo Hello, world!
      - name: run model 
        run: python linear-model.py
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
